services:
  app:
    image: my_dnd_bot
    build: "."
    restart: unless-stopped
    volumes:
      - db-data:/app/db
      - ./dnd_helper:/app/dnd_helper
    entrypoint: python dnd_helper/main.py

volumes:
  db-data:
